CREATE TABLE History (
	ArticleID INTEGER PRIMARY KEY AUTOINCREMENT,
	Title VARCHAR(50) NOT NULL,
	Description VARCHAR(100) NOT NULL,
	Content TEXT NOT NULL,
	Active BOOL DEFAULT TRUE
);

CREATE TABLE Users (
	UserID INTEGER PRIMARY KEY AUTOINCREMENT,
	Name VARCHAR(50) NOT NULL,
	Surname VARCHAR(50) NOT NULL,
	Email VARCHAR(50) NOT NULL,
	Password VARCHAR(50) NOT NULL,
	Role VARCHAR(50) DEFAULT 'user',
	Active BOOL DEFAULT TRUE,
	PRIMARY KEY (UserID)
);

CREATE TABLE Events (
	EventID INTEGER PRIMARY KEY AUTOINCREMENT,
	Title VARCHAR(50) NOT NULL,
	Subtitle VARCHAR(50) NOT NULL,
	Description TEXT NOT NULL,
	Date DATE NOT NULL,
	StartTime TIME NOT NULL,
	EndTime TIME NOT NULL,
	SeatsNumber INT NOT NULL,
	Active BOOL DEFAULT TRUE,
	PRIMARY KEY (EventID)
);

CREATE TABLE Credits (
	StafferID INTEGER PRIMARY KEY AUTOINCREMENT,
	Name VARCHAR(50) NOT NULL,
	Surname VARCHAR(50) NOT NULL,
	Role VARCHAR(50) NOT NULL,
	Active BOOL DEFAULT TRUE,
	PRIMARY KEY (StafferID)
);